# Generated by Django 6.0.3 on 2026-06-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_experience_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripAttraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(default=1)),
                ('sequence', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_attractions',
                'ordering': ['day_number', 'sequence'],
            },
        ),

        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='content.city'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['public_id'], name='idx_states_public_id'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='idx_states_name'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='content.state'),
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='content.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripattraction',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.experience'),
        ),
        migrations.AddField(
            model_name='tripattraction',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_attractions', to='content.trip'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['public_id'], name='idx_cities_public_id'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='idx_cities_name'),
        ),
        migrations.AlterUniqueTogether(
            name='tripattraction',
            unique_together={('trip', 'experience')},
        ),
    ]
