# Generated by Django 6.0.3 on 2026-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_category_id_experience_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='experience',
            name='idx_experience_category_id',
        ),
        migrations.RemoveIndex(
            model_name='experience',
            name='idx_category_is_open',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='pricing_rul_experie_86bb9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='pricing_composite_idx',
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category'], name='idx_experience_category_id'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category', 'is_open'], name='idx_category_is_open'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['experience'], name='pricing_rul_experie_86bb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['experience', 'ticket_type', 'valid_from', 'valid_to'], name='pricing_composite_idx'),
        ),
    ]
