# Generated by Django 6.0.3 on 2026-06-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_collection_collectionexperience_provider_tickettype_and_more'),
    ]

    operations = [
        # 1. Rename model Location to City
        migrations.RenameModel(
            old_name='Location',
            new_name='City',
        ),
        # 2. Alter db table of City to 'cities'
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        # 3. Remove old Location indexes from City model
        migrations.RemoveIndex(
            model_name='city',
            name='idx_locations_public_id',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='idx_locations_name',
        ),
        # 4. Add new fields to City
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        # 5. Create State model
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('best_time', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        # 6. Add state FK to City
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='content.state'),
        ),
        # 7. Add indexes to State and City
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['public_id'], name='idx_states_public_id'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='idx_states_name'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['public_id'], name='idx_cities_public_id'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='idx_cities_name'),
        ),
        # 8. Explicitly alter Experience/Trip location fields to point to City model
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='content.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='content.city'),
        ),
    ]
