# Generated by Django 5.1.4 on 2026-06-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_experience_location_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['id']},
        ),
    ]
