# Generated by Django 5.1.4 on 2026-07-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_city_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant_confirmation', models.BooleanField(default=True)),
                ('requires_manual_confirmation', models.BooleanField(default=False)),
                ('cancellation_allowed', models.BooleanField(default=True)),
                ('cancellation_before_hours', models.IntegerField(default=24)),
                ('refund_allowed', models.BooleanField(default=True)),
                ('validity_type', models.CharField(choices=[('fixed', 'Fixed'), ('relative', 'Relative')], default='fixed', max_length=50)),
                ('validity_duration', models.DurationField(blank=True, null=True)),
                ('slot_booking_required', models.BooleanField(default=True)),
                ('qr_reusable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policy', to='content.tickettype')),
            ],
            options={
                'db_table': 'booking_policies',
            },
        ),
        migrations.CreateModel(
            name='ExperienceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='content.experience')),
            ],
            options={
                'db_table': 'experience_highlights',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProviderBookingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_individual_booking', models.IntegerField(default=10)),
                ('max_group_booking', models.IntegerField(default=20)),
                ('allow_bulk_booking', models.BooleanField(default=True)),
                ('require_manual_bulk_approval', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('require_phone_verification', models.BooleanField(default=False)),
                ('require_captcha', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_configuration', to='content.provider')),
            ],
            options={
                'db_table': 'provider_booking_configurations',
            },
        ),
        migrations.CreateModel(
            name='ExperienceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='content.experience')),
            ],
            options={
                'db_table': 'experience_attributes',
                'ordering': ['display_order'],
                'unique_together': {('experience', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TicketFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion'), ('requirement', 'Requirement')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_features', to='content.tickettype')),
            ],
            options={
                'db_table': 'ticket_features',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['ticket_type'], name='idx_feature_ticket_type'), models.Index(fields=['feature_type'], name='idx_feature_feature_type')],
            },
        ),
    ]
