# Generated by Django 6.0.3 on 2026-07-22 13:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_bookingpolicy_experiencehighlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingException',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Specific date for operating exception')),
                ('is_closed', models.BooleanField(default=True, help_text='True if closed on this date')),
                ('opening_time', models.TimeField(blank=True, help_text='Overridden opening time (NULL if closed)', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Overridden closing time (NULL if closed)', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for closure/change (e.g., Maintenance, Republic Day)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operating_exceptions',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='operatinghours',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='operatinghours',
            name='operating_h_experie_db494d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='base_price',
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='General daily closing time', null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='friday',
            field=models.BooleanField(default=True, help_text='Open on Friday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='monday',
            field=models.BooleanField(default=True, help_text='Open on Monday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='General daily opening time', null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='saturday',
            field=models.BooleanField(default=True, help_text='Open on Saturday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='sunday',
            field=models.BooleanField(default=True, help_text='Open on Sunday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='thursday',
            field=models.BooleanField(default=True, help_text='Open on Thursday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='tuesday',
            field=models.BooleanField(default=True, help_text='Open on Tuesday'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='wednesday',
            field=models.BooleanField(default=True, help_text='Open on Wednesday'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='age_category',
            field=models.CharField(choices=[('Any', 'Any'), ('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant'), ('Senior', 'Senior'), ('Student', 'Student')], default='Any', help_text='Age category for this ticket type', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='nationality_category',
            field=models.CharField(choices=[('Any', 'Any'), ('Indian', 'Indian'), ('SAARC', 'SAARC'), ('BIMSTEC', 'BIMSTEC'), ('Others', 'Others')], default='Any', help_text='Nationality category for this ticket type', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price for this ticket type including all charges', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='id',
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='experience',
            field=models.OneToOneField(help_text='Monument/Experience these general hours apply to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operating_hours', serialize=False, to='content.experience'),
        ),
        migrations.AddField(
            model_name='operatingexception',
            name='experience',
            field=models.ForeignKey(help_text='Experience this exception applies to', on_delete=django.db.models.deletion.CASCADE, related_name='operating_exceptions', to='content.experience'),
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='closes_at',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='opens_at',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='special_closure_reason',
        ),
        migrations.AddIndex(
            model_name='operatingexception',
            index=models.Index(fields=['experience', 'date'], name='operating_e_experie_9a8331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatingexception',
            unique_together={('experience', 'date')},
        ),
    ]
