# Generated by Django 5.1.4 on 2026-07-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('travel_agency', 'Travel Agency'), ('school', 'School'), ('college', 'College'), ('corporate', 'Corporate'), ('government', 'Government'), ('ngo', 'NGO'), ('tour_operator', 'Tour Operator'), ('other', 'Other')], default='other', max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprises',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('booking_manager', 'Booking Manager'), ('finance', 'Finance'), ('viewer', 'Viewer')], default='viewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user.enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_memberships', to='user.user_data')),
            ],
            options={
                'db_table': 'enterprise_members',
                'unique_together': {('enterprise', 'user')},
            },
        ),
    ]
