# Generated by Django 5.1.4 on 2026-07-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_bookingpolicy_experiencehighlight_and_more'),
        ('user', '0002_enterprise_enterprisemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to='user.user_data')),
            ],
            options={
                'db_table': 'provider_members',
                'unique_together': {('provider', 'user')},
            },
        ),
    ]
