# Generated by Django 6.0.3 on 2026-04-14 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_remove_experience_idx_experience_category_id_and_more'),
        ('user', '0003_alter_user_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete', null=True)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.experience')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.user_data')),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(fields=['experience_id'], name='idx_reviews_experience_id'), models.Index(fields=['user_id'], name='idx_reviews_user_id'), models.Index(fields=['experience_id', 'created_at'], name='idx_reviews_experience_created_at'), models.Index(fields=['rating'], name='idx_reviews_rating')],
            },
        ),
    ]
