# Generated by Django 6.0.3 on 2026-04-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='idx_rev_exp_created_at',
            old_name='idx_reviews_experience_created_at',
        ),
    ]
