# Generated by Django 5.1.4 on 2026-07-09 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_inventory'),
        ('content', '0007_bookingpolicy_experiencehighlight_and_more'),
        ('user', '0002_enterprise_enterprisemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('booking_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bulk_requests', to='user.user_data')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_requests', to='user.enterprise')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.experience')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_requests', to='user.user_data')),
            ],
            options={
                'db_table': 'bulk_booking_requests',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('specific-date', 'Specific Date'), ('range', 'Range')], max_length=20)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content.tickettype')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=50)),
                ('seat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.schedule')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
    ]
