# Generated by Django 6.0.3 on 2026-07-22 13:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_payment_booking'),
        ('content', '0008_operatingexception_alter_operatinghours_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nationality_category', models.CharField(blank=True, choices=[('Any', 'Any'), ('Indian', 'Indian'), ('SAARC', 'SAARC'), ('BIMSTEC', 'BIMSTEC'), ('Others', 'Others')], default='Any', help_text='Nationality category for this item', max_length=20, null=True)),
                ('age_category', models.CharField(blank=True, choices=[('Any', 'Any'), ('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant'), ('Senior', 'Senior'), ('Student', 'Student')], default='Any', help_text='Age category for this item', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TicketTypeSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_type_schedules',
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='uq_experience_inventory_date',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_experience',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_date',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_is_closed',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_booking_98f7e3_idx',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='available_capacity',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='inventory',
            name='blocked_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cancelled_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='confirmed_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 7, 22, 13, 37, 10, 330247, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='content.tickettype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='used_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content.experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.BooleanField(default=False, help_text='Applies on Friday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.BooleanField(default=False, help_text='Applies on Monday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.BooleanField(default=False, help_text='Applies on Saturday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.BooleanField(default=False, help_text='Applies on Sunday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.BooleanField(default=False, help_text='Applies on Thursday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.BooleanField(default=False, help_text='Applies on Tuesday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.BooleanField(default=False, help_text='Applies on Wednesday'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(help_text='Booking this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='ticket_type',
            field=models.ForeignKey(help_text='Ticket type associated with this booking item', on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='content.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_item',
            field=models.ForeignKey(blank=True, help_text='Booking item this ticket was issued for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='booking.bookingitem'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking_item_id'], name='tickets_booking_c0789b_idx'),
        ),
        migrations.AddField(
            model_name='tickettypeschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_schedules', to='booking.schedule'),
        ),
        migrations.AddField(
            model_name='tickettypeschedule',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_schedules', to='content.tickettype'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Scheduled time slot for this booking item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='booking.tickettypeschedule'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='booking.tickettypeschedule'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['ticket_type'], name='idx_inventory_ticket_type'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['date'], name='idx_inventory_date'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_open'], name='idx_inventory_is_open'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reserved_capacity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddIndex(
            model_name='tickettypeschedule',
            index=models.Index(fields=['ticket_type'], name='ticket_type_ticket__0dd077_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettypeschedule',
            index=models.Index(fields=['schedule'], name='ticket_type_schedul_162950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettypeschedule',
            unique_together={('ticket_type', 'schedule')},
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['booking_id'], name='booking_ite_booking_b3bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['ticket_type_id'], name='booking_ite_ticket__146509_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['time_slot_id'], name='booking_ite_time_sl_0f1d0c_idx'),
        ),
    ]
