# Generated by Django 6.0.3 on 2026-04-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20260329_1024'),
        ('booking', '0006_merge_20260405_1043'),
    ]

    operations = [
    ]
