# Generated by Django 6.0.3 on 2026-04-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_merge_20260414_0634'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_user_id_b89769_idx',
            old_name='payments_user_id_1b771c_idx',
        ),
    ]
